---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: 'L"opérateur Trident vous permet de personnaliser l"installation d"Astra Trident à l"aide des attributs du `TridentOrchestrator` spécifications' 
---
= Personnalisez le déploiement des opérateurs Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


L'opérateur Trident vous permet de personnaliser l'installation d'Astra Trident à l'aide des attributs du `TridentOrchestrator` spécifications

Consultez le tableau suivant pour obtenir la liste des attributs :

[cols="3"]
|===
| Paramètre | Description | Valeur par défaut 


| `namespace` | Espace de noms pour installer Astra Trident dans | « par défaut » 


| `debug` | Activez le débogage pour Astra Trident | faux 


| `IPv6` | Installez Astra Trident sur IPv6 | faux 


| `k8sTimeout` | Délai d'expiration pour les opérations Kubernetes | 30 secondes 


| `silenceAutosupport` | N'envoyez pas automatiquement des packs AutoSupport à NetApp | faux 


| `enableNodePrep` | Gérer automatiquement les dépendances des nœuds de travail (*BÊTA*) | faux 


| `autosupportImage` | Image conteneur pour la télémétrie AutoSupport | « netapp/trident-autosupport :21.04.0 » 


| `autosupportProxy` | Adresse/port d'un proxy pour l'envoi de télémétrie AutoSupport | "http://proxy.example.com:8888"[] 


| `uninstall` | Indicateur utilisé pour désinstaller Astra Trident | faux 


| `logFormat` | Format de connexion Astra Trident à utiliser [text,json] | « texte » 


| `tridentImage` | Image Astra Trident à installer | netapp/trident:21.04 


| `imageRegistry` | Chemin d'accès au registre interne, du format
`<registry FQDN>[:port][/subpath]` | "k8s.gcr.io/sig-storage (k8s 1.19+) ou quay.io/k8scsi" 


| `kubeletDir` | Chemin d'accès au répertoire kubelet de l'hôte | “/var/lib/kubelet” 


| `wipeout` | Liste des ressources à supprimer pour effectuer la suppression complète d'Astra Trident |  


| `imagePullSecrets` | Secrets pour extraire des images d'un registre interne |  


| `controllerPluginNodeSelector` | Sélecteurs de nœud supplémentaires pour les pods exécutant le plug-in Trident Controller CSI. Suit le même format que pod.spec.nodeSelector. | Pas de valeur par défaut ; facultatif 


| `controllerPluginTolerations` | Remplace les tolérances pour les pods exécutant le plug-in Trident Controller CSI. Suit le même format que pod.spec.tolérances. | Pas de valeur par défaut ; facultatif 


| `nodePluginNodeSelector` | Sélecteurs de nœud supplémentaires pour les pods exécutant le plug-in Trident Node CSI. Suit le même format que pod.spec.nodeSelector. | Pas de valeur par défaut ; facultatif 


| `nodePluginTolerations` | Remplace les tolérances pour les pods exécutant le plug-in Trident Node CSI. Suit le même format que pod.spec.tolérances. | Pas de valeur par défaut ; facultatif 
|===

IMPORTANT: `spec.namespace` est spécifié dans `TridentOrchestrator` Pour indiquer quel espace de noms Astra Trident est installé dans. Ce paramètre *ne peut pas être mis à jour après l'installation d'Astra Trident*. Si vous essayez de le faire, l'état de `TridentOrchestrator` pour passer à `Failed`. Astra Trident n'est pas conçu pour être migré entre les espaces de noms.


TIP: Pour plus d'informations sur le formatage des paramètres du pod, reportez-vous à la section link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Attribution de pods aux nœuds"^].

Vous pouvez utiliser les attributs mentionnés ci-dessus lors de la définition `TridentOrchestrator` pour personnaliser votre installation. Voici un exemple :

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
Voici un autre exemple illustrant le déploiement possible de Trident avec les sélecteurs de nœuds :

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
Si vous cherchez à personnaliser l'installation au-delà de quoi `TridentOrchestrator` les arguments permettent, vous devez envisager d'utiliser `tridentctl` Pour générer des manifestes YAML personnalisés que vous pouvez modifier si nécessaire.
